spring:
  application:
    #服务名称
    name: user

eureka:
  client:
    #服务注册中心的地址
    service-url:
      defaultZone: http://eureka5001.com:5001/eureka/,http://eureka5002.com:5002/eureka/
  instance:
    #实例名称
    hostname: localhost