spring:
  application:
    #服务名称
    name: product
  # sleuth 全链路追踪配置
  sleuth:
    # 取样配置
    sampler:
      # 取样比例，默认 0.1
      probability: 1.0
      # 每秒取样次数 10
      rate: 10
  zipkin:
    # zipkin 全链路追踪-取样数据收集服务器
    base-url: http://127.0.0.1:9520
  boot:
    # 服务监控
    admin:
      client:
        url: http://127.0.0.1:9001

eureka:
  client:
    #服务注册中心的地址
    service-url:
      defaultZone: http://eureka5001.com:5001/eureka/,http://eureka5002.com:5002/eureka/
  instance:
    #实例名称
    hostname: localhost


# actuator 服务监控配置
management:
  endpoints:
    web:
      exposure:
        #配置暴露的端点，如果配置为 * ，则暴露所有 actuator 的健康监控端点
        #include: hystrix.stream,info,health
        include: "*"
        #不暴露的端点
        exclude: env