server:
  port: 3001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 开始配置路由
      routes:
        - id: redisRateLimiter-server
          # 转发路径 http://localhost:6001 或者 lb://user (这是服务发现的方式，可以负载到不同的用户服务器)
          uri: lb://user
          # 断言配置
          predicates:
            - Path=/user/**
          filters:
            - name: RequestRateLimiter
              # 参数
              args:
                # 每秒发放令牌个数
                redis-rate-limiter.replenishRate: 1
                # 令牌桶容量
                redis-rate-limiter.burstCapacity: 2
                # 新建令牌桶
                key-resolver: "#{@pathKeyResolver}"
      discovery:
        locator:
          # 是否启用服务发现
          enabled: true
          # 是否
          lower-case-service-id: true
  redis:
    host: 192.168.99.101
    lettuce:
      pool:
        max-active: 20
        max-wait: 2000ms
        min-idle: 5
        max-idle: 10

resilience4j:
  ratelimiter:
    limiters:
      user:
        # 限定时期内允许通行的请求数量
        limitForPeriod: 2
        # 限定时期（单位毫秒）
        limitRefreshPeriod: 10000
        # 超时时间（单位毫秒）
        timeoutDuration: 1000

eureka:
  client:
    #服务注册中心的地址
    service-url:
      defaultZone: http://localhost:5001/eureka,http://localhost:5002/eureka
